### ISSUE TITLE
关于元器件推荐咨询以及3D模型

### ISSUE THREAD

**Issue by zhiwenwu** [peng-zhihui/Peak#1]
大佬，有推荐的元器件链接吗？还有大佬的3D建模用的是哪款软件吗？

**Comment by peng-zhihui** [comment]
是说元器件库吗？我一般都是自己画的

**Comment by peng-zhihui** [comment]
> 这个是8PIN接插屏幕吗？找了好长时间。有老铁有推荐链接吗？

https://detail.tmall.com/item.htm?id=607394513826&_u=a2hql9gc2718

**Comment by mascg** [comment]
> > > 这个是8PIN接插屏幕吗？找了好长时间。有老铁有推荐链接吗？
> > 
> > 
> > https://detail.tmall.com/item.htm?id=607394513826&_u=a2hql9gc2718
> 
> 呜呜，是屏幕链接，怪我没说清楚

https://github.com/FASTSHIFT/X-TRACK/tree/main/Hardware
X-TRACK 用的这个屏幕，应该可以参考下

**Comment by peng-zhihui** [comment]
就是上面这款

**Comment by zhiwenwu** [comment]
> 就是上面这款
https://github.com/FASTSHIFT/X-TRACK/tree/main/Hardware
大佬，我按照这块屏幕购买的硬件，发现这款不是FFC/FPC接口的，请问您这8PIN的硬件，是有增加转接板吗？如果没有转接板的话，能帮忙看下具体购买链接？
