### ISSUE TITLE
关于供电切换电路问题

### ISSUE THREAD

**Issue by yuzhou3996** [peng-zhihui/Peak#10]
![image](https://user-images.githubusercontent.com/31774471/137933951-68d81ab9-6bb4-410b-a70d-63de8da1fb7c.png)
**你好，想问一下，这里在电池供电的时候Q1会导通吗，这是怎么实现供电自动切换功能的呢**

**Comment by AaronChuzb** [comment]
其实我也看不太懂这里的电路设计，对mos管应用不太多，PWR_EN给高电平时，Q2 nmos会被导通，此时的Q1的G极为低电平，从而被短路，也就是不会有电流从VBAT_IN流向VBAT，但是这看上去貌似跟切换供电没什么关联，可能我的理解是错误的吧，然后就是VBAT一直连着R2,R4两个分压电阻哪怕关机电路也在一直耗电可能是设计上的一点小缺陷吧。

**Comment by peng-zhihui** [comment]
Q1不是做电源切换的，是用来控制电池供电的开关，当开机键按下之后导通反之关断，而开机之后的一秒内由软件控制PWR_EN的IO拉高进行保持，松开按键之后就不会断电了。

**Comment by AaronChuzb** [comment]
> Q1不是做电源切换的，是用来控制电池供电的开关，当开机键按下之后导通反之关断，而开机之后的一秒内由软件控制PWR_EN的IO拉高进行保持，松开按键之后就不会断电了。

稚晖君我偶尔看到一个方案不知道这样行不行，

<img width="537" alt="Snipaste_2021-10-20_13-59-48" src="https://user-images.githubusercontent.com/45120061/138036555-9d4d6fd0-c735-48ab-99e1-bd52b3ff4a8d.png">

**Comment by yuzhou3996** [comment]
我理解稚晖君的意思了。
开关连接到EC_KEY引脚，当没有按下开关的时候，Q1的G极被上拉，此时Q1不导通，不进行供电。
开关按下的时候，EC_KEY引脚拉低，此时Q1的G极被拉低为二极管的压降大约0.3V，Q1导通，芯片上电
芯片上电以后，将PWR_EN拉高，此时Q2导通，Q1的G极一直被拉低，所以开关再次松开也不会断电了
但是还有个问题想请教一下，EC_KEY_DET的作用是什么呢？还希望稚晖君能帮忙解答

**Comment by yuzhou3996** [comment]
好的，多谢解答
