### ISSUE TITLE
请教一下，稚晖君你的开发环境是什么？

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [peng-zhihui/Peak#15]
不知道稚晖君，你是用什么IDE开发的ESP32程序？是在Windows平台还是别的平台？
我现在对着这份代码，不知道怎么去编译它。。

**Comment by peng-zhihui** [comment]
了解一下platformio，windows下编译，安装好环境直接用vscode打开项目文件夹就能编译了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BeeeeeeLazy ***@***.***&gt;
发送时间: 2021年10月30日 15:21
收件人: peng-zhihui/Peak ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/Peak] 请教一下，稚晖君你的开发环境是什么？ (Issue #15)
