### ISSUE TITLE
下载的工程编译后报错，提示没有freertos文件 还有fat文件系统也有错误。

### ISSUE THREAD

**Issue by givemethree** [peng-zhihui/Peak#24]
1.freertos  报错内容
******************************************************************

 #include "FreeRTOS.h"
          ^~~~~~~~~~~~
compilation terminated.
In file included from src/App/Accounts/ACT_IMU.cpp:2:
src/HAL/HAL.h:9:10: fatal error: FreeRTOS.h: No such file or directory

2.注释freertos文件后编译报fat 错误。

lib/SD/src/sd_diskio.cpp:825:18: error: 'ff_diskio_impl_t' does not name a type
     static const ff_diskio_impl_t sd_impl = {
                  ^~~~~~~~~~~~~~~~
lib/SD/src/sd_diskio.cpp:832:31: error: 'sd_impl' was not declared in this scope
     ff_diskio_register(pdrv, &sd_impl);
                               ^~~~~~~
lib/SD/src/sd_diskio.cpp:832:31: note: suggested alternative: 'fdiml'
     ff_diskio_register(pdrv, &sd_impl);
                               ^~~~~~~
                               fdiml
lib/SD/src/sd_diskio.cpp:832:5: error: 'ff_diskio_register' was not declared in this scope
     ff_diskio_register(pdrv, &sd_impl);
     ^~~~~~~~~~~~~~~~~~
lib/SD/src/sd_diskio.cpp:832:5: note: suggested alternative: 'lv_disp_drv_register'
     ff_diskio_register(pdrv, &sd_impl);
     ^~~~~~~~~~~~~~~~~~
     lv_disp_drv_register
*** [.pio\build\pico32\libbbe\SD\sd_diskio.cpp.o] Error 1

**Comment by givemethree** [comment]
platform 安装方式的问题，重新按照标准安装方式安装platformio后 再编译就没问题了  
标准安装方式： https://blog.csdn.net/JR_Smmon/article/details/120856365

**Comment by givemethree** [comment]
问题关闭

**Comment by jiuwei000** [comment]
> platform 安装方式的问题，重新按照标准安装方式安装platformio后 再编译就没问题了 标准安装方式： https://blog.csdn.net/JR_Smmon/article/details/120856365

我遇到了和你一样的问题，请问解决的关键点就是按这篇博文写的那样做么？我照着做了之后仍然报错没有freertos头文件。。。

**Comment by FChong96** [comment]
我也遇到了相同的问题，缺少头文件，如果注释掉的话会出fat 错误。重装了Platform并没有解决问题。

**Comment by jiuwei000** [comment]
> 

问题解决了，esp32的platform用3.5版本

**Comment by FChong96** [comment]
> > 
> 
> 问题解决了，esp32的platform用3.5版本
我也试一下，freertos头文件需要注释掉吗

**Comment by MXuanZero** [comment]
> > 
> 
> 解决了，esp32的平台问题用3.5版本

请教一下，怎么安装3.5版本？我没找到相关的安装途径。
谢谢！

**Comment by MXuanZero** [comment]
问题解决了，上面的解决方法试了一遍不太行，如果有人没解决的话可以去看我这个[issues](https://github.com/peng-zhihui/Peak/issues/28#issuecomment-1222158709)。
https://github.com/peng-zhihui/Peak/issues/28#issuecomment-1222158709
